// .res entries ():
cs_assault.wad
cs_bdog.wad
cs_office.wad
cstrike.wad
decals.wad
gfx/env/ntdm1_bk.tga
gfx/env/ntdm1_dn.tga
gfx/env/ntdm1_ft.tga
gfx/env/ntdm1_lf.tga
gfx/env/ntdm1_rt.tga
gfx/env/ntdm1_up.tga
halflife.wad
models/w_c4.mdl
models/zombie_anthill/billboard.mdl
models/zombie_anthill/billboard2.mdl
models/zombie_anthill/bus_stop.mdl
models/zombie_anthill/bush1.mdl
models/zombie_anthill/car_01.mdl
models/zombie_anthill/car_02.mdl
models/zombie_anthill/car_bombed.mdl
models/zombie_anthill/car_furgon.mdl
models/zombie_anthill/car_old.mdl
models/zombie_anthill/car_police1.mdl
models/zombie_anthill/car_police2.mdl
models/zombie_anthill/car_truck1.mdl
models/zombie_anthill/couch_01.mdl
models/zombie_anthill/dead_1.mdl
models/zombie_anthill/dead_2.mdl
models/zombie_anthill/forest1.mdl
models/zombie_anthill/hostage.mdl
models/zombie_anthill/lamppost.mdl
models/zombie_anthill/sing_02.mdl
models/zombie_anthill/table_01.mdl
models/zombie_anthill/trace_barrel01.mdl
models/zombie_anthill/trash_clothing01.mdl
models/zombie_anthill/trash_junk_02.mdl
models/zombie_anthill/trup1.mdl
models/zombie_anthill/trup2.mdl
models/zombie_anthill/trup3.mdl
models/zombie_anthill/trup4.mdl
models/zombie_anthill/trup5.mdl
sound/ambience/alarm1.wav
sound/ambience/silo_wind_loop.wav
sound/as_resident_evil/resident_evil_main_theme.wav
sound/zombie_anthill/fire1.wav
sound/zombie_anthill/m134_shoot1.wav
sound/zombie_anthill/truck1.wav
sprites/flame.spr
maps/zm_anthill_city.res
maps/zm_anthill_city.txt
maps/zm_anthill_city_detail.txt
maps/zm_anthill_city.nav
gfx/detail/dt_metal1.tga
gfx/detail/dt_metal2.tga
gfx/detail/dt_conc.tga
gfx/detail/dt_ground2.tga
gfx/detail/dt_ssteel1.tga
gfx/detail/dt_brick.tga
gfx/detail/dt_rock1.tga
gfx/detail/dt_wood1.tga
gfx/detail/dt_ground3.tga
gfx/detail/dt_plaster2.tga
gfx/detail/dt_smooth1.tga
