gfx/env/xt_deheatbk.tga
gfx/env/xt_deheatdn.tga
gfx/env/xt_deheatft.tga
gfx/env/xt_deheatlf.tga
gfx/env/xt_deheatrt.tga
gfx/env/xt_deheatup.tga
models/de_desertcomplex/bush34v.mdl
models/de_desertcomplex/fence_01.mdl
models/de_desertcomplex/gins_deskchair.mdl
models/de_desertcomplex/gins_palm240_256.mdl
models/de_desertcomplex/gins_palmfam600_256.mdl
models/de_desertcomplex/hessi_regal.mdl
models/de_desertcomplex/light.mdl
models/de_desertcomplex/pe_el10.mdl
models/de_desertcomplex/pipe01.mdl
models/de_desertcomplex/rock01.mdl
models/de_desertcomplex/rock02.mdl
models/de_desertcomplex/rock03.mdl
models/de_desertcomplex/table01.mdl
models/de_desertcomplex/w_m4a1.mdl
sound/de_desertcomplex/hwind01.wav
sound/de_desertcomplex/hwind02.wav
sound/de_desertcomplex/industrial2.wav
sound/de_desertcomplex/industrial3.wav
sound/de_desertcomplex/industrial4.wav
sound/de_desertcomplex/industrial5.wav
sound/de_desertcomplex/industrial6.wav
sound/de_desertcomplex/light1.wav
sound/de_desertcomplex/pipe01.wav
sound/de_desertcomplex/pipe02.wav
sound/de_desertcomplex/rock2.wav
sound/de_desertcomplex/wind02.wav
maps/zm_desertcomplex.txt
maps/zm_desertcomplex_detail.txt
overviews/zm_desertcomplex.bmp
overviews/zm_desertcomplex.txt
